name: MobLimiter
version: '${project.version}'
main: tropaeo.com.moblimiter.MobLimiter
api-version: 1.13
authors: [ Tropaeo ]
description: Lightweight plugin that lets you remove certain mob types from spawning
commands:
  mlreload:
    description: Reload the MobLimiter plugin.
    usage: /<command>
    aliases:
      - mlreload

